db:
    image: mysql:5.7.7
    volumes_from:
        - dbdata
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
        - "3306:3306"
dbdata:
    image: busybox
    volumes:
        - /var/lib/mysql
web:
    image: rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
        - .:/myapp
    ports:
        - "3000:3000"
    links:
        - db
    volumes_from:
        - bundle
bundle:
    image: rails
    volumes:
        - /bundle
